# Generated by Django 6.0.4 on 2026-05-05 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('status_change', 'Status Changed'), ('fee_waived', 'Fee Waived'), ('pledge_verified', 'Pledge Verified'), ('car_released', 'Car Released'), ('damage_assessed', 'Damage Assessed')], max_length=30)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('none', 'No Damage'), ('minor', 'Minor (Scratches/Dents)'), ('moderate', 'Moderate (Panel Damage)'), ('major', 'Major (Structural)'), ('total_loss', 'Total Loss')], default='none', max_length=20)),
                ('description', models.TextField()),
                ('location_on_car', models.CharField(max_length=200)),
                ('estimated_repair_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_assessment', 'Under Assessment'), ('cost_determined', 'Cost Determined'), ('paid', 'Paid'), ('waived', 'Waived by Admin'), ('disputed', 'Disputed')], default='reported', max_length=30)),
                ('waiver_reason', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='loans.loan')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_damages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DamagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='damage/photos/')),
                ('photo_type', models.CharField(choices=[('before', 'Before Trip'), ('after', 'After Trip'), ('damage', 'Damage Close-up')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('damage_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='damage.damagereport')),
            ],
        ),
    ]
