# Generated by Django 6.0.4 on 2026-05-05 08:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vin_number', models.CharField(max_length=50, unique=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_valuation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_deposit_percentage', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_loan', 'On Loan'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired'), ('pending_inspection', 'Pending Inspection')], default='available', max_length=30)),
                ('mileage', models.IntegerField(default=0)),
                ('fuel_type', models.CharField(default='Petrol', max_length=30)),
                ('transmission', models.CharField(default='Automatic', max_length=20)),
                ('seat_capacity', models.IntegerField(default=5)),
                ('primary_photo', models.ImageField(blank=True, null=True, upload_to='cars/primary/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.carcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fleet.car')),
            ],
        ),
    ]
