# Generated by Django 6.0.4 on 2026-05-05 08:52

import django.db.models.deletion
import loans.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('pledge_type', models.CharField(choices=[('title_deed', 'Property Title Deed'), ('logbook', 'Vehicle Logbook'), ('bank_guarantee', 'Bank Guarantee Letter'), ('other', 'Other Asset')], max_length=30)),
                ('asset_description', models.TextField()),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('document_front', models.FileField(upload_to='pledges/documents/')),
                ('document_back', models.FileField(blank=True, null=True, upload_to='pledges/documents/')),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='pledges/supporting/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('verified', 'Verified & Accepted'), ('rejected', 'Rejected'), ('returned', 'Returned to Owner')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_pledges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('expected_return_date', models.DateTimeField()),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_days', models.IntegerField()),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('extension_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('damage_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pickup_code', models.CharField(default=loans.models.generate_pickup_code, max_length=10, unique=True)),
                ('status', models.CharField(choices=[('pending_pledge', 'Awaiting Pledge Verification'), ('pledge_verified', 'Pledge Verified - Awaiting Pickup'), ('active', 'Active / Car Picked Up'), ('overdue', 'Overdue'), ('returned', 'Returned - Awaiting Inspection'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending_pledge', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='fleet.car')),
                ('pickup_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_confirmations', to=settings.AUTH_USER_MODEL)),
                ('pledge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='loans.pledge')),
            ],
        ),
    ]
